name: community.solidfire Ansible CI

on:
  push:
  # pull_request:
  # schedule:
  #  - cron: '0 6 * * *'

jobs:
  sanity:
    name: Sanity (${{ matrix.ansible }} on Solidfire
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ansible:
          - stable-2.20
          - devel

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:          
          python-version: 3.12

      - name: Install ansible-core for stable matrix
        if: matrix.ansible == 'stable-2.20'
        run: pip install 'ansible-core==2.20.1' --disable-pip-version-check

      - name: Install ansible from devel for devel matrix
        if: matrix.ansible == 'devel'
        run: pip install https://github.com/ansible/ansible/archive/devel.tar.gz --disable-pip-version-check

      - name: Cleanup workspace
        run: |
          rm -rf .venv tests/output || true

      - name: Debug workspace listing
        run: |
          pwd
          ls -la

      - name: Make directory to make ansible-test happy
        run: |
          pwd
          mkdir -p ansible_collections/community/solidfire/
          rsync -av . ansible_collections/community/solidfire/ --exclude ansible_collections/community/solidfire/ --exclude .git

      - name: Run sanity tests Solidfire
        run: ansible-test sanity --docker -v --color
        working-directory: ansible_collections/community/solidfire/
      - name: Run Unit Tests
        run: ansible-test units --docker -v --color
        working-directory: ansible_collections/community/solidfire/